name: "Snyk Container Test"

on:
  push:
    branches:
      - master

jobs:
  Pipeline-Job:
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env:  
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
    steps:
    # Checkout Code - Updated to a recent, stable version
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js 14.x
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    # install snyk and snyk-to-html - Updated to a recent, stable version
    - name: Snyk Action
      uses: snyk/actions/setup@v1.4.0
      
    - name: Snyk-to-html
      run: npm install -g snyk-to-html
          
    # Docker Build
    - name: Build Container      
      run: |
        docker build .  -t andrewsouthard1/juiceshop:main
        
    # Run Snyk Container Test - Corrected the snyk-to-html command
    - name: Snyk Container Test
      id: snyk_container_test_step
      run: |
        snyk container test --json --file=Dockerfile andrewsouthard1/juiceshop:main --severity-threshold=high > results-container.json
        snyk-to-html -i results-container.json -o results-container.html
      continue-on-error: true
      
    # Run Snyk Container Monitor - This step is good
    - name: Snyk Container Monitor
      run: |
        snyk container monitor andrewsouthard1/juiceshop:main
      continue-on-error: true
      
    - name: Upload snyk html
      uses: actions/upload-artifact@v4.6.1
      with:
        name: snyk-results
        path: |
          ./results-container.html
      
    # Set up QEMU - Updated to a recent, stable version
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
      
    # Set up Docker Buildx - Updated to a recent, stable version
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
              
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5.0.0
      with:
        push: true
        tags: andrewsouthard1/juiceshop:main
