name: "Snyk Code Test"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - uses: snyk/actions/setup@master
    - name: Snyk Action
      run: |
         sudo npm install -g snyk-to-html
    - name: Snyk code test
      run: snyk code test --json-file-output=results-code.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
    - name: confirm json
      run: cat results-code.json
    - name: snyk-to-html
      run: snyk-to-html -i results-code.json -o results-code.html
    - name: test snyk-to-html
      run:  if command -v snyk-to-html &> /dev/null; then
                   snyk-to-html -i results-code.json -o results-code.html --debug
               else
                  echo "snyk-to-html not found"
                  exit 1
              fi
    - name: Upload html output
      uses: actions/upload-artifact@v4.6.1
      with:
       name: results-code.html
       path: ./results-code.html
