name: "Snyk Code Test pipeline"

on:
  push:
    branches:
      - master

jobs:
  Pipeline-Job:
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Snyk
      uses: snyk/actions/setup@v2

    - name: Install Snyk CLI 
      run: npm install -g snyk

    - name: Snyk Code Test
      run: snyk code test --json-file-output=results-code.json
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true

    - name: Confirm JSON output
      run: cat results-code.json

    - name: Install snyk-to-html 
      run: npm install snyk-to-html

    - name: Convert JSON to HTML
      run:  snyk-to-html -i results-code.json -o results-code.html --debug

    - name: Upload HTML output
      uses: actions/upload-artifact@v4
      with:
        name: results-code.html
        path: ./results-code.html
