name: "Snyk Open Source"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Open Source'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Snyk Action
      run: |
         sudo npm install -g snyk
         sudo npm install -g snyk-to-html
      continue-on-error: true
    # Run Snyk Open Source
    - name: Run Snyk Open Source
      run: |
         snyk test --severity-threshold=high --all-projects --json 
         snyk-to-html -o ./results.html
      continue-on-error: true
    - name: Snyk Open Source Monitor
      run: |
         snyk monitor --severity-threshold=high --all-projects
      continue-on-error: true
   # Upload Artifact   
    - name: Upload html output
      uses: actions/upload-artifact@v4.6.1
      with:
       name: results.html
       path: ./results.html
