name: "Snyk Code Test"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: snyk/actions/setup@master
    - name: Snyk Action
      run: npm install -g snyk-to-html
    - name: Snyk code test
      run: snyk code test --severity-threshold=high --json-file-output=results-code.json
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Run Minimal snyk-to-html Test
      run: |
        chmod +x test-snyk-html.sh
        ./test-snyk-html.sh
    - name: confirm json
      run: cat results-code.json
    - name: Debug - List Files
      run: ls -l
    - name: check json perms
      run: getfacl results-code.json
    - name: test snyk-to-html
      run:  snyk-to-html -i $(pwd)/results-code.json -o results-code.html
    - name: Upload html output
      uses: actions/upload-artifact@v4
      with:
       name: results-code.html
       path: results-code.html
