name: "Snyk Container Test"

on:
  push:
    branches:
    - master

jobs:
  Pipeline-Job:
    # Configure Environment
    name: 'Snyk Test'
    runs-on: ubuntu-latest
    env: 
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
       
    steps:
    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v1

    # Install and Authenticate to Snyk
    - name: Install Snyk & Authenticate
      run: |
         sudo npm install -g snyk
         snyk auth ${SNYK_TOKEN}
         
    # Docker Build
    - name: Build Container     
      run: |
         docker build .  -t andrewsouthard1/juiceshop:main
         
    # Run Snyk Container Test     
    - name: Snyk Container Test
      run: |
         snyk container test --json --file=Dockerfile andrewsouthard1/juiceshop:main  --severity-threshold=high | snyk-to-html -o results-container.html
      continue-on-error: true
      
    # Run Snyk Container Monitor     
    - name: Snyk Container Monitor
      run: |
         snyk container monitor andrewsouthard1/juiceshop:main
      continue-on-error: true
      
    - name: Upload snyk html
      uses: actions/upload-artifact@v4.6.1
      with:
        name: snyk-results
        path: |
          ./results-container.html
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
             
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: andrewsouthard1/juiceshop:main
